language: node_js
node_js:
  - 'node'
script:
  - yarn test --collectCoverage
  - yarn run codecov
cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: release
      deploy:
        provider: npm
        email: george.aidonidis@gmail.com
        api_key: $NPM_TOKEN
        branches:
          only:
            - master
        script:
          - yarn semantic-release
